### ISSUE TITLE
Doesn't work with Akka.Streams v. 1.3.5

### ISSUE THREAD

**Issue by trimsane** [AkkaNetContrib/Akka.Streams.Kafka#16]
Method not found: 'Void Akka.Streams.Stage.GraphStageLogic.SetHandler(Akka.Streams.Inlet, System.Action, System.Action, System.Action`1<System.Exception>)'.

   at Akka.Streams.Kafka.Stages.ProducerStageLogic`2..ctor(ProducerStage`2 stage, Attributes attributes)
   at Akka.Streams.Kafka.Stages.ProducerStage`2.CreateLogic(Attributes inheritedAttributes)
   at Akka.Streams.Stage.GraphStage`1.CreateLogicAndMaterializedValue(Attributes inheritedAttributes)
   at Akka.Streams.Implementation.Fusing.GraphAssembly.Materialize(Attributes inheritedAttributes, IModule[] copiedModules, IDictionary`2 materializedValues, Action`1 register)
   at Akka.Streams.Implementation.ActorMaterializerImpl.ActorMaterializerSession.MaterializeGraph(GraphModule graph, Attributes effectiveAttributes, IDictionary`2 materializedValues)
   at Akka.Streams.Implementation.ActorMaterializerImpl.ActorMaterializerSession.MaterializeAtomic(AtomicModule atomic, Attributes effectiveAttributes, IDictionary`2 materializedValues)
   at Akka.Streams.Implementation.MaterializerSession.MaterializeModule(IModule module, Attributes effectiveAttributes)

It's looks like Akka.Stream API was changed and SetHanlder 'Void Akka.Streams.Stage.GraphStageLogic.SetHandler(Akka.Streams.Inlet, System.Action, System.Action, System.Action`1<System.Exception>)' was removed.

**Comment by marcpiechura** [comment]
@trimsane You’re right, this was changed in the last version in order to provide a better type safety, see https://github.com/akkadotnet/akka.net/pull/3237 for details. It’s probably an easy fix, just need to use `Inlet<T>` instead of `Inlet` , might want to send a PR ?

**Comment by trimsane** [comment]
@marcpiechura Yes, I want

**Comment by trimsane** [comment]
@marcpiechura AkkaNetContrib/Akka.Streams.Kafka/pull/17
